// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuPW9fJ0fKA4bnYPnd_HXw6y0PehF6aWg',
    appId: '1:246139021105:web:f7a43d99d3ea99f8583210',
    messagingSenderId: '246139021105',
    projectId: 'chat-app-115f2',
    authDomain: 'chat-app-115f2.firebaseapp.com',
    storageBucket: 'chat-app-115f2.appspot.com',
    measurementId: 'G-4VZSHPMCMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYYtgdh0K3-Mk3aBxBdtw-F2Dmdkckt4',
    appId: '1:246139021105:android:748e486ae0289a2f583210',
    messagingSenderId: '246139021105',
    projectId: 'chat-app-115f2',
    storageBucket: 'chat-app-115f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZEX2VEbptg7v34HFSrgGiYi_b0mtmNI',
    appId: '1:246139021105:ios:d051f109e5a2e78b583210',
    messagingSenderId: '246139021105',
    projectId: 'chat-app-115f2',
    storageBucket: 'chat-app-115f2.appspot.com',
    iosClientId: '246139021105-7aaqmi3hi3art7v5h6rpl1r0ilir4u9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fristproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASZEX2VEbptg7v34HFSrgGiYi_b0mtmNI',
    appId: '1:246139021105:ios:188ccb7f9a710628583210',
    messagingSenderId: '246139021105',
    projectId: 'chat-app-115f2',
    storageBucket: 'chat-app-115f2.appspot.com',
    iosClientId: '246139021105-ljup82qg2jfjujjmkghraiq6o34d6tkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fristproject.RunnerTests',
  );
}
